version: '3.4'

networks:
  commander-api-dev:
    driver: bridge

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=Commander
    networks:
      - commander-api-dev
    ports:
      - "9999:5432"
    restart: unless-stopped
#    volumes:
#      - database-data:/var/lib/postgresql/data/
    
  commander_api:
    depends_on:
      - postgresql_database
    image: galambborong/commander:0.9
    ports:
      - "8080:80"
    environment: 
      - Logging__Console__FormatterName=""
      - DB_CONNECTION_STRING="User ID = postgres;Password=passwd;Host=host.docker.internal;Port=9999;Database=Commander;Integrated Security=true;Pooling=true"
#      - "User ID=postgres;Password=passwd;Host=postgresql_database;Port=9999;Database=Commander;Pooling=true"
#      - DB_CONNECTION_STRING="User ID=postgres;Password=passwd;Host=postgresql_database;Port=9999;Database=Commander;Pooling=true"
#      - User ID = user;Password=pass;Server=postgres;Port=5432;Database=testdb;Integrated Security=true;Pooling=true
    
    #User ID=postgres;Password=passwd;Host=postgresql_database;Port=9999;Database=Commander;Pooling=true;
    networks:
      - commander-api-dev
    restart: unless-stopped

volumes:
  database-data: