// <auto-generated />
using Commander.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Commander.Migrations
{
    [DbContext(typeof(CommanderContext))]
    [Migration("20220326170854_UpdateSeedData")]
    partial class UpdateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commander.Models.Alias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandAlias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.ToTable("Aliases");
                });

            modelBuilder.Entity("Commander.Models.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdminPrivilegesRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("HowTo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Commands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminPrivilegesRequired = false,
                            HowTo = "Check git repository status",
                            Line = "git status",
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 2,
                            AdminPrivilegesRequired = false,
                            HowTo = "Check disk usage",
                            Line = "df -h",
                            PlatformId = 1
                        },
                        new
                        {
                            Id = 3,
                            AdminPrivilegesRequired = false,
                            HowTo = "Run Docker Image in background; removing container once finished; with nice logging format",
                            Line = "docker run -d --rm -p <ext>:<int> -e Logging__Console__FormatterName=\"\" <namespace>/<image>:<tag>",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 4,
                            AdminPrivilegesRequired = false,
                            HowTo = "List current Docker processes (containers)",
                            Line = "docker ps",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 5,
                            AdminPrivilegesRequired = false,
                            HowTo = "Build Docker image from Dockerfile",
                            Line = "docker build <pwd> -t <namespace>/<image>:<tag>",
                            PlatformId = 6
                        });
                });

            modelBuilder.Entity("Commander.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Linux"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DotNet"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shell"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arduino"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Docker"
                        });
                });

            modelBuilder.Entity("Commander.Models.Alias", b =>
                {
                    b.HasOne("Commander.Models.Command", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");
                });

            modelBuilder.Entity("Commander.Models.Command", b =>
                {
                    b.HasOne("Commander.Models.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });
#pragma warning restore 612, 618
        }
    }
}
